### ISSUE TITLE
No release/tag for 0.6.2

### ISSUE THREAD

**Issue by RossGammon** [thlorenz/inline-source-map#17]
Hi,
I am looking to package inline-source-map in Debian, but I notice 0.6.2 is available at npmjs.com, but the last release here on Github is 0.6.1.
Is there any chance of a retrospective release on github? In Debian, we prefer to take the tarballs from here.
Regards,
Ross

**Comment by legobeat** [comment]
Years later, there is now a tagged release of [`0.6.2`](https://github.com/thlorenz/inline-source-map/releases/tag/v0.6.2).

**Comment by legobeat** [comment]
Update: [`0.6.3`](https://github.com/thlorenz/inline-source-map/releases/tag/v0.6.3) now also has a tagged release.
