### ISSUE TITLE
Tests fail with tap version 8.0.0

### ISSUE THREAD

**Issue by RossGammon** [thlorenz/inline-source-map#18]
Debian recently updated tap to 8.0.0. This has caused node-inline-source-map to fail to build:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844938
There is a link to the full build log in the Debian bug. An extract showing the first failure:
not ok 5 - test unfinished: generated mappings
          ---
          at:
            line: 25
            column: 1
            file: test/inline-source-map.js
          source: |
            test('generated mappings', function (t) {
          ...
        1..5
        # failed 1 of 5 tests
    not ok 1 - generated mappings # time=37.7ms
      ---
      at:
        line: 25
        column: 1
        file: test/inline-source-map.js
      results:
        plan:
          start: 1
          end: 5
        count: 5
        pass: 4
        ok: false
        fail: 1
        time: 37.7
      source: |
        test('generated mappings', function (t) {
      ...

I have push a branch to my fork with tap set to v8.0.0, and you can see the build failure on Travis here:
https://travis-ci.org/RossGammon/inline-source-map/jobs/178408294

I would be grateful of any help to fix this, as Debian plans to release early in the New Year.

**Comment by thlorenz** [comment]
Sorry, but tap is pinned to version `~0.7` or so, so they run just fine.
Not sure why you're trying to use a different one.

**Comment by RossGammon** [comment]
According to Travis, Kapouer's PR builds fine with Tap 0.7 as well as working locally here with Tap 8.0.0. So it would be safe to merge this PR without bumping the tap version. Then everyone wins :-)
In Debian, we prefer not to waste space with lots of different (old) copies of the same library, and use a modern version of the library, installed globally.

**Comment by thlorenz** [comment]
> In Debian, we prefer not to waste space with lots of different (old) copies of the same library, and use a modern version of the library, installed globally.

That's not how node and node modules + npm work.
Not merging this as it's not the package's problem but due to the fact that Debian decided to do things differently than the rest of the community. Why do you think we have a package.json in there specifying the version ranges of each dependency?

Better to rethink your way of doing things, otherwise you'll run into this problem over and over ...

**Comment by kapouer** [comment]
@thlorenz you still believe what you're saying ? come on ! wake up !

**Comment by kapouer** [comment]
you know perfectly well code deduplication is a good thing.

**Comment by thlorenz** [comment]
Yes I agree code deduplication is hot and dependency hell is even hotter 🤒
